### ISSUE TITLE
Clinic Based Conditional Access To Patient Dashboard

### ISSUE THREAD

**Issue by SNMeans** [NeffCodes/retinopathy-risk-assessment-tool#35]
Restrict access to patient records based on clinic affiliation, allowing doctors to view only patients associated with their respective clinic. (for ex: doctors at clinic 'A' can only see patients of clinic 'A'-doctors at clinic 'B' can only see patients of clinic 'B')

**Tasks**
1.  Add 'clinic' attribute to the 'patients' model
2.  Extend existing auth(ticket #5) to clinic filtering
     -  With the ```@login-required``` decorator, add a custom permission check based on user's assigned clinic (patient/views)
     -  Retrieve the authenticated user's clinic
     -  Filter database query so that only patient records from this clinic are displayed
     -  **May have to update the nav bar/dashboard display? Not sure**
3. Test log-in as different users to make sure this access control works

**Acceptance Criteria**

- [x] The Patient model includes a clinic field to record clinic affiliation.
- [x] The patient dashboard filters patient data based on the logged-in doctor’s clinic.
- [x] Only doctors from a specific clinic can view patient records associated with that clinic.
- [x] Unauthorized access results in an error message or empty results.
~~The navbar dynamically displays the dashboard link only for logged-in, clinic-affiliated doctors.~~ Moved to #40 

**Aim to complete by Monday Nov 18**

**Comment by NeffCodes** [comment]
Estimated Completion Date = Friday 11/8, PR later in the day
